# deploy/manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: placeholder
          image: 003729975368.dkr.ecr.us-west-2.amazonaws.com/production-ai-platform/knowledge-service:51dcd23fce625e26b7430fcd65917bc9921a0424
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: placeholder
  namespace: dev
spec:
  selector:
    app: placeholder
  ports:
    - port: 80
      targetPort: 80